name: dotnet package

on: [push]

jobs:
   build:

      runs-on: ubuntu-latest
      strategy:
      matrix:
         dotnet-version: '5.0.x'

      steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-dotnet@v1.8.2
            with:
            dotnet-version: '5.0.x'
         - run: dotnet build
         - name: Setup .NET Core SDK            
         - name: Install dependencies
            run: dotnet restore
         - name: Build
            run: dotnet build --configuration Release --no-restore
         - name: Test
            run: dotnet test --no-restore --verbosity normal